"""L0 — the kernel.

Pure: no I/O, no third-party imports, nothing above it in the stack. Enforced by an
``import-linter`` contract rather than by convention, because in every surveyed
codebase this discipline existed at the start and decayed in all of them.

Everything here is a value object or a protocol. The kernel decides nothing on its
own; it defines the vocabulary the capability layer above it decides *with*.
"""

from __future__ import annotations

from attest.kernel.actions import Action
from attest.kernel.attestation import (
    Attestation,
    AttestationError,
    CostRecord,
    EffectRecord,
)
from attest.kernel.audit import (
    AuditEvent,
    ChainVerification,
    ChainVerifier,
    EventType,
    RunSeal,
)
from attest.kernel.authority import (
    MAX_GRANT_TTL,
    ApprovalRecord,
    AuthorizationGrant,
    Discharge,
    GrantCheck,
    GrantRejection,
    Obligation,
    ObligationOutcome,
)
from attest.kernel.canonical import NULL_HASH, Canonical, CanonicalisationError
from attest.kernel.config import AssuranceTier, AttestConfig, ModelTier
from attest.kernel.context import (
    ExecutionContext,
    IdentitySnapshot,
    ModelRef,
    ProfileRef,
    TenantBinding,
)
from attest.kernel.effects import (
    TERMINAL_EFFECT_STATES,
    EffectClass,
    EffectClasses,
    EffectSemantics,
    EffectState,
    IdempotencyMode,
)
from attest.kernel.errors import (
    ApprovalStoreError,
    AttestError,
    AuditSinkError,
    BudgetStoreError,
    ConfigurationError,
    ContractViolation,
    IntegrityError,
    KernelError,
    RetrieverScopeError,
    SealError,
    SignatureError,
    StoreError,
)
from attest.kernel.evidence import (
    CORE_EVIDENCE_KINDS,
    AuthorityLevel,
    Evidence,
    EvidenceKind,
    EvidenceKinds,
    Persistence,
    SourceRef,
    SourceType,
    SupportResult,
    ValidityWindow,
    VerificationOutcome,
)
from attest.kernel.identifiers import (
    ActorId,
    ApprovalId,
    AttestationId,
    CorpusId,
    DatasetId,
    EvidenceId,
    GrantId,
    Hash,
    Nonce,
    PromptId,
    RunId,
    SubjectId,
    TenantId,
)
from attest.kernel.ports import (
    ApprovalStore,
    AuditSink,
    BudgetStore,
    Clock,
    IdGenerator,
    MemoryStore,
    NonceStore,
    Retriever,
    RunStore,
    Sealer,
    Signer,
)
from attest.kernel.verdicts import (
    CORE_REFUSAL_REASONS,
    POST_EFFECT_VERDICTS,
    Refusal,
    RefusalReason,
    Verdict,
)
from attest.kernel.warrants import (
    CORE_WARRANTS,
    Finding,
    Severity,
    WarrantKind,
    WarrantKinds,
    WarrantPolicy,
    WarrantReport,
    WarrantStatus,
)

__all__ = [
    "CORE_EVIDENCE_KINDS",
    "CORE_REFUSAL_REASONS",
    "CORE_WARRANTS",
    "MAX_GRANT_TTL",
    "NULL_HASH",
    "POST_EFFECT_VERDICTS",
    "TERMINAL_EFFECT_STATES",
    "Action",
    "ActorId",
    "ApprovalId",
    "ApprovalRecord",
    "ApprovalStore",
    "ApprovalStoreError",
    "AssuranceTier",
    "AttestConfig",
    "AttestError",
    "Attestation",
    "AttestationError",
    "AttestationId",
    "AuditEvent",
    "AuditSink",
    "AuditSinkError",
    "AuthorityLevel",
    "AuthorizationGrant",
    "BudgetStore",
    "BudgetStoreError",
    "Canonical",
    "CanonicalisationError",
    "ChainVerification",
    "ChainVerifier",
    "Clock",
    "ConfigurationError",
    "ContractViolation",
    "CorpusId",
    "CostRecord",
    "DatasetId",
    "Discharge",
    "EffectClass",
    "EffectClasses",
    "EffectRecord",
    "EffectSemantics",
    "EffectState",
    "EventType",
    "Evidence",
    "EvidenceId",
    "EvidenceKind",
    "EvidenceKinds",
    "ExecutionContext",
    "Finding",
    "GrantCheck",
    "GrantId",
    "GrantRejection",
    "Hash",
    "IdGenerator",
    "IdempotencyMode",
    "IdentitySnapshot",
    "IntegrityError",
    "KernelError",
    "MemoryStore",
    "ModelRef",
    "ModelTier",
    "Nonce",
    "NonceStore",
    "Obligation",
    "ObligationOutcome",
    "Persistence",
    "ProfileRef",
    "PromptId",
    "Refusal",
    "RefusalReason",
    "Retriever",
    "RetrieverScopeError",
    "RunId",
    "RunSeal",
    "RunStore",
    "SealError",
    "Sealer",
    "Severity",
    "SignatureError",
    "Signer",
    "SourceRef",
    "SourceType",
    "StoreError",
    "SubjectId",
    "SupportResult",
    "TenantBinding",
    "TenantId",
    "ValidityWindow",
    "Verdict",
    "VerificationOutcome",
    "WarrantKind",
    "WarrantKinds",
    "WarrantPolicy",
    "WarrantReport",
    "WarrantStatus",
]
