# Generated by Django 6.0.7 on 2026-07-31 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="BudgetReservation",
            fields=[
                (
                    "reservation_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("scope", models.CharField(db_index=True, max_length=128)),
                ("amount", models.DecimalField(decimal_places=6, max_digits=20)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "db_table": "attest_budget_reservations",
            },
        ),
        migrations.CreateModel(
            name="BudgetSpend",
            fields=[
                (
                    "scope",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=6, default=0, max_digits=20),
                ),
                (
                    "ceiling",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
                ),
            ],
            options={
                "db_table": "attest_budget_spend",
            },
        ),
        migrations.CreateModel(
            name="RedeemedNonce",
            fields=[
                (
                    "nonce",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("grant_id", models.CharField(db_index=True, max_length=128)),
                ("redeemed_at", models.DateTimeField()),
            ],
            options={
                "db_table": "attest_redeemed_nonces",
            },
        ),
        migrations.CreateModel(
            name="RevokedGrant",
            fields=[
                (
                    "grant_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("revoked_at", models.DateTimeField()),
                ("reason", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "attest_revoked_grants",
            },
        ),
        migrations.CreateModel(
            name="AttestationRecord",
            fields=[
                (
                    "run_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=128)),
                ("verdict", models.CharField(db_index=True, max_length=32)),
                ("answer", models.TextField(blank=True, default="")),
                ("warnings", models.JSONField(default=list)),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("payload", models.BinaryField()),
                ("is_final", models.BooleanField(default=False)),
                ("sealed", models.BooleanField(default=False)),
                ("seal_signature", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(db_index=True)),
                (
                    "supersedes",
                    models.CharField(blank=True, db_index=True, default="", max_length=128),
                ),
                (
                    "superseded_by",
                    models.CharField(blank=True, db_index=True, default="", max_length=128),
                ),
            ],
            options={
                "db_table": "attest_attestations",
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "created_at"],
                        name="attest_atte_tenant__09a365_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditEventRecord",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("run_id", models.CharField(db_index=True, max_length=128)),
                ("event_type", models.CharField(max_length=64)),
                ("occurred_at", models.DateTimeField()),
                ("payload", models.BinaryField()),
                ("sequence", models.IntegerField(blank=True, null=True)),
                (
                    "previous_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
            ],
            options={
                "db_table": "attest_audit_events",
                "indexes": [
                    models.Index(
                        fields=["run_id", "sequence"],
                        name="attest_audi_run_id_7a6bca_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AutonomyPolicy",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant_id", models.CharField(db_index=True, max_length=128)),
                ("capability", models.CharField(max_length=128)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("auto", "auto"),
                            ("approve", "approve"),
                            ("blocked", "blocked"),
                        ],
                        default="approve",
                        max_length=16,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.CharField(blank=True, default="", max_length=128),
                ),
            ],
            options={
                "db_table": "attest_autonomy_policies",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "capability"),
                        name="attest_autonomy_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MemoryRecord",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant_id", models.CharField(db_index=True, max_length=128)),
                (
                    "subject_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=128),
                ),
                ("content", models.TextField()),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "attest_memory",
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "subject_id"],
                        name="attest_memo_tenant__018859_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PendingAction",
            fields=[
                (
                    "approval_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("run_id", models.CharField(db_index=True, max_length=128)),
                ("tenant_id", models.CharField(db_index=True, max_length=128)),
                ("grant_id", models.CharField(max_length=128)),
                ("action_hash", models.CharField(max_length=64)),
                ("summary", models.TextField(blank=True, default="")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                            ("expired", "expired"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("opened_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("approver", models.CharField(blank=True, default="", max_length=128)),
            ],
            options={
                "db_table": "attest_pending_actions",
                "indexes": [
                    models.Index(
                        fields=["state", "expires_at"],
                        name="attest_pend_state_23bb51_idx",
                    )
                ],
            },
        ),
    ]
