# Generated by Django 6.0.7 on 2026-07-31 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attest", "0002_guards"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetspend",
            name="reservation_seq",
            field=models.BigIntegerField(default=0),
        ),
    ]
