# Generated by Django 6.0.7 on 2026-07-31 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attest", "0003_budget_reservation_seq"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingaction",
            name="approver_role",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="pendingaction",
            name="requested_by",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
