# Generated by Django 6.0.7 on 2026-07-31 23:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attest", "0004_budget_reservation_seq"),
    ]

    operations = [
        migrations.AddField(
            model_name="memoryrecord",
            name="author",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="memoryrecord",
            name="author_is_human",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="memoryrecord",
            name="expires_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="memoryrecord",
            name="memory_class",
            field=models.CharField(db_index=True, default="fact", max_length=16),
        ),
        migrations.AddField(
            model_name="memoryrecord",
            name="origin_run",
            field=models.CharField(blank=True, db_index=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="memoryrecord",
            name="source_attestation",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
