# Generated by Django 6.0.7 on 2026-08-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attest", "0005_memory_provenance"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueuedRun",
            fields=[
                (
                    "run_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=128)),
                ("actor_id", models.CharField(max_length=128)),
                ("envelope", models.BinaryField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("running", "running"),
                            ("held", "held"),
                            ("done", "done"),
                            ("failed", "failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("attempt", models.IntegerField(default=1)),
                ("submitted_at", models.DateTimeField(db_index=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("detail", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "attest_queued_runs",
                "indexes": [
                    models.Index(
                        fields=["state", "submitted_at"],
                        name="attest_queu_state_2a15b9_idx",
                    )
                ],
            },
        ),
    ]
