# Generated by Django 6.0.7 on 2026-08-01 00:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attest", "0006_queued_runs"),
    ]

    operations = [
        migrations.CreateModel(
            name="DispatchEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("dispatch_id", models.CharField(db_index=True, max_length=128)),
                (
                    "run_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=128),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=128)),
                ("event_type", models.CharField(db_index=True, max_length=64)),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("attempt", models.IntegerField(default=1)),
                ("actor", models.CharField(blank=True, default="", max_length=128)),
                ("detail", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "attest_dispatch_events",
            },
        ),
        migrations.AddField(
            model_name="queuedrun",
            name="latest_run_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="queuedrun",
            name="lease_expires_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="queuedrun",
            name="worker_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddIndex(
            model_name="queuedrun",
            index=models.Index(
                fields=["state", "lease_expires_at"],
                name="attest_queu_state_f2c133_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dispatchevent",
            index=models.Index(
                fields=["dispatch_id", "occurred_at"],
                name="attest_disp_dispatc_6c40bb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dispatchevent",
            index=models.Index(
                fields=["tenant_id", "occurred_at"],
                name="attest_disp_tenant__f1a999_idx",
            ),
        ),
    ]
