# Generated by Django 6.0.7 on 2026-08-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attest", "0008_dispatch_guards"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingaction",
            name="redeemed_by_grant",
            field=models.CharField(blank=True, db_index=True, default="", max_length=128),
        ),
    ]
