# Generated by Django 6.0.7 on 2026-08-01 01:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attest", "0009_approval_consumption"),
    ]

    operations = [
        migrations.CreateModel(
            name="SealedRun",
            fields=[
                (
                    "run_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("sealed_at", models.DateTimeField(db_index=True)),
                ("event_count", models.IntegerField()),
                ("head_hash", models.CharField(max_length=64)),
            ],
            options={
                "db_table": "attest_sealed_runs",
            },
        ),
    ]
